//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming

export interface IBookingApiClient {

    bookingAppointments_GetAvailableSlots(slug: string, date?: string | undefined, employeeId?: string | undefined, serviceIds?: string[] | undefined): Promise<AppointmentSlotDto[]>;

    bookingAppointments_GetMonthAvailability(slug: string, year?: number | undefined, month?: number | undefined, employeeId?: string | undefined, serviceIds?: string[] | undefined): Promise<BookingMonthAvailabilityDto>;

    bookingEmployees_GetEmployees(slug: string, serviceIds?: string[] | undefined): Promise<BookingEmployeeDto[]>;

    bookingInspirations_AttachInspiration(slug: string, appointmentId: string, uploadToken?: string | null | undefined, file?: FileParameter | null | undefined): Promise<UploadInspirationResponse>;

    bookingServiceCategories_GetServiceCategories(slug: string): Promise<ServiceCategoryDto[]>;

    bookingServices_GetServices(slug: string, categoryId?: string | null | undefined, employeeId?: string | null | undefined): Promise<BookingServiceDto[]>;

    bookingServices_GetService(id: string, slug: string): Promise<BookingServiceDto>;

    publicCreateAppointment_PublicCreateHold(slug: string, request: CreateAppointmentDto): Promise<PublicBookingHoldDto>;

    publicCreateAppointment_PublicUpdateAppointment(slug: string, request: UpdateAppointmentDto, id: string): Promise<HoldLease>;

    publicBookingDomain_Resolve(host?: string | undefined): Promise<PublicBookingSalonInfoDto>;

    publicBookingSalon_Get(slug: string): Promise<PublicBookingSalonInfoDto>;

    publicClientDiagnostics_ReportClientError(request: ClientErrorReportRequest): Promise<void>;

    publicOtp_RequestOtp(slug: string, id: string, request: RequestOtpRequest): Promise<FileResponse>;

    publicOtp_VerifyOtp(slug: string, id: string, request: VerifyOtpRequest): Promise<VerifyOtpResult>;

    publicOtp_ConfirmWithSession(slug: string, id: string, request: ConfirmWithSessionRequest): Promise<VerifyOtpResult>;

    publicSelfService_RequestOtp(slug: string, request: SelfServiceContactRequest): Promise<FileResponse>;

    publicSelfService_VerifyOtp(slug: string, request: SelfServiceVerifyRequest): Promise<SelfServiceVerifyResponse>;

    publicSelfService_List(slug: string): Promise<SelfServiceAppointmentDto[]>;

    publicSelfService_Cancel(slug: string, id: string): Promise<FileResponse>;

    publicSelfService_Reschedule(slug: string, id: string, request: SelfServiceRescheduleRequest): Promise<FileResponse>;
}

export class BookingApiClient implements IBookingApiClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "";
    }

    bookingAppointments_GetAvailableSlots(slug: string, date?: string | undefined, employeeId?: string | undefined, serviceIds?: string[] | undefined): Promise<AppointmentSlotDto[]> {
        let url_ = this.baseUrl + "/api/booking/{slug}/appointments/available-slots?";
        if (slug === undefined || slug === null)
            throw new globalThis.Error("The parameter 'slug' must be defined.");
        url_ = url_.replace("{slug}", encodeURIComponent("" + slug));
        if (date === null)
            throw new globalThis.Error("The parameter 'date' cannot be null.");
        else if (date !== undefined)
            url_ += "date=" + encodeURIComponent("" + date) + "&";
        if (employeeId === null)
            throw new globalThis.Error("The parameter 'employeeId' cannot be null.");
        else if (employeeId !== undefined)
            url_ += "employeeId=" + encodeURIComponent("" + employeeId) + "&";
        if (serviceIds === null)
            throw new globalThis.Error("The parameter 'serviceIds' cannot be null.");
        else if (serviceIds !== undefined)
            serviceIds && serviceIds.forEach(item => { url_ += "serviceIds=" + encodeURIComponent("" + item) + "&"; });
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processBookingAppointments_GetAvailableSlots(_response);
        });
    }

    protected processBookingAppointments_GetAvailableSlots(response: Response): Promise<AppointmentSlotDto[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as AppointmentSlotDto[];
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<AppointmentSlotDto[]>(null as any);
    }

    bookingAppointments_GetMonthAvailability(slug: string, year?: number | undefined, month?: number | undefined, employeeId?: string | undefined, serviceIds?: string[] | undefined): Promise<BookingMonthAvailabilityDto> {
        let url_ = this.baseUrl + "/api/booking/{slug}/appointments/month-availability?";
        if (slug === undefined || slug === null)
            throw new globalThis.Error("The parameter 'slug' must be defined.");
        url_ = url_.replace("{slug}", encodeURIComponent("" + slug));
        if (year === null)
            throw new globalThis.Error("The parameter 'year' cannot be null.");
        else if (year !== undefined)
            url_ += "year=" + encodeURIComponent("" + year) + "&";
        if (month === null)
            throw new globalThis.Error("The parameter 'month' cannot be null.");
        else if (month !== undefined)
            url_ += "month=" + encodeURIComponent("" + month) + "&";
        if (employeeId === null)
            throw new globalThis.Error("The parameter 'employeeId' cannot be null.");
        else if (employeeId !== undefined)
            url_ += "employeeId=" + encodeURIComponent("" + employeeId) + "&";
        if (serviceIds === null)
            throw new globalThis.Error("The parameter 'serviceIds' cannot be null.");
        else if (serviceIds !== undefined)
            serviceIds && serviceIds.forEach(item => { url_ += "serviceIds=" + encodeURIComponent("" + item) + "&"; });
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processBookingAppointments_GetMonthAvailability(_response);
        });
    }

    protected processBookingAppointments_GetMonthAvailability(response: Response): Promise<BookingMonthAvailabilityDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as BookingMonthAvailabilityDto;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<BookingMonthAvailabilityDto>(null as any);
    }

    bookingEmployees_GetEmployees(slug: string, serviceIds?: string[] | undefined): Promise<BookingEmployeeDto[]> {
        let url_ = this.baseUrl + "/api/booking/{slug}/employees?";
        if (slug === undefined || slug === null)
            throw new globalThis.Error("The parameter 'slug' must be defined.");
        url_ = url_.replace("{slug}", encodeURIComponent("" + slug));
        if (serviceIds === null)
            throw new globalThis.Error("The parameter 'serviceIds' cannot be null.");
        else if (serviceIds !== undefined)
            serviceIds && serviceIds.forEach(item => { url_ += "serviceIds=" + encodeURIComponent("" + item) + "&"; });
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processBookingEmployees_GetEmployees(_response);
        });
    }

    protected processBookingEmployees_GetEmployees(response: Response): Promise<BookingEmployeeDto[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as BookingEmployeeDto[];
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<BookingEmployeeDto[]>(null as any);
    }

    bookingInspirations_AttachInspiration(slug: string, appointmentId: string, uploadToken?: string | null | undefined, file?: FileParameter | null | undefined): Promise<UploadInspirationResponse> {
        let url_ = this.baseUrl + "/api/booking/{slug}/appointments/{appointmentId}/inspirations";
        if (slug === undefined || slug === null)
            throw new globalThis.Error("The parameter 'slug' must be defined.");
        url_ = url_.replace("{slug}", encodeURIComponent("" + slug));
        if (appointmentId === undefined || appointmentId === null)
            throw new globalThis.Error("The parameter 'appointmentId' must be defined.");
        url_ = url_.replace("{appointmentId}", encodeURIComponent("" + appointmentId));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = new FormData();
        if (file !== null && file !== undefined)
            content_.append("file", file.data, file.fileName ? file.fileName : "file");

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "X-Inspiration-Upload-Token": uploadToken !== undefined && uploadToken !== null ? "" + uploadToken : "",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processBookingInspirations_AttachInspiration(_response);
        });
    }

    protected processBookingInspirations_AttachInspiration(response: Response): Promise<UploadInspirationResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as UploadInspirationResponse;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<UploadInspirationResponse>(null as any);
    }

    bookingServiceCategories_GetServiceCategories(slug: string): Promise<ServiceCategoryDto[]> {
        let url_ = this.baseUrl + "/api/booking/{slug}/service-categories";
        if (slug === undefined || slug === null)
            throw new globalThis.Error("The parameter 'slug' must be defined.");
        url_ = url_.replace("{slug}", encodeURIComponent("" + slug));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processBookingServiceCategories_GetServiceCategories(_response);
        });
    }

    protected processBookingServiceCategories_GetServiceCategories(response: Response): Promise<ServiceCategoryDto[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as ServiceCategoryDto[];
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ServiceCategoryDto[]>(null as any);
    }

    bookingServices_GetServices(slug: string, categoryId?: string | null | undefined, employeeId?: string | null | undefined): Promise<BookingServiceDto[]> {
        let url_ = this.baseUrl + "/api/booking/{slug}/services?";
        if (slug === undefined || slug === null)
            throw new globalThis.Error("The parameter 'slug' must be defined.");
        url_ = url_.replace("{slug}", encodeURIComponent("" + slug));
        if (categoryId !== undefined && categoryId !== null)
            url_ += "categoryId=" + encodeURIComponent("" + categoryId) + "&";
        if (employeeId !== undefined && employeeId !== null)
            url_ += "employeeId=" + encodeURIComponent("" + employeeId) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processBookingServices_GetServices(_response);
        });
    }

    protected processBookingServices_GetServices(response: Response): Promise<BookingServiceDto[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as BookingServiceDto[];
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<BookingServiceDto[]>(null as any);
    }

    bookingServices_GetService(id: string, slug: string): Promise<BookingServiceDto> {
        let url_ = this.baseUrl + "/api/booking/{slug}/services/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        if (slug === undefined || slug === null)
            throw new globalThis.Error("The parameter 'slug' must be defined.");
        url_ = url_.replace("{slug}", encodeURIComponent("" + slug));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processBookingServices_GetService(_response);
        });
    }

    protected processBookingServices_GetService(response: Response): Promise<BookingServiceDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as BookingServiceDto;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<BookingServiceDto>(null as any);
    }

    publicCreateAppointment_PublicCreateHold(slug: string, request: CreateAppointmentDto): Promise<PublicBookingHoldDto> {
        let url_ = this.baseUrl + "/api/booking/{slug}/public-appointment/hold";
        if (slug === undefined || slug === null)
            throw new globalThis.Error("The parameter 'slug' must be defined.");
        url_ = url_.replace("{slug}", encodeURIComponent("" + slug));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(request);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processPublicCreateAppointment_PublicCreateHold(_response);
        });
    }

    protected processPublicCreateAppointment_PublicCreateHold(response: Response): Promise<PublicBookingHoldDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as PublicBookingHoldDto;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<PublicBookingHoldDto>(null as any);
    }

    publicCreateAppointment_PublicUpdateAppointment(slug: string, request: UpdateAppointmentDto, id: string): Promise<HoldLease> {
        let url_ = this.baseUrl + "/api/booking/{slug}/public-appointment/{id}";
        if (slug === undefined || slug === null)
            throw new globalThis.Error("The parameter 'slug' must be defined.");
        url_ = url_.replace("{slug}", encodeURIComponent("" + slug));
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(request);

        let options_: RequestInit = {
            body: content_,
            method: "PATCH",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processPublicCreateAppointment_PublicUpdateAppointment(_response);
        });
    }

    protected processPublicCreateAppointment_PublicUpdateAppointment(response: Response): Promise<HoldLease> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as HoldLease;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<HoldLease>(null as any);
    }

    publicBookingDomain_Resolve(host?: string | undefined): Promise<PublicBookingSalonInfoDto> {
        let url_ = this.baseUrl + "/api/booking-domains/resolve?";
        if (host === null)
            throw new globalThis.Error("The parameter 'host' cannot be null.");
        else if (host !== undefined)
            url_ += "host=" + encodeURIComponent("" + host) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processPublicBookingDomain_Resolve(_response);
        });
    }

    protected processPublicBookingDomain_Resolve(response: Response): Promise<PublicBookingSalonInfoDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as PublicBookingSalonInfoDto;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<PublicBookingSalonInfoDto>(null as any);
    }

    publicBookingSalon_Get(slug: string): Promise<PublicBookingSalonInfoDto> {
        let url_ = this.baseUrl + "/api/booking/{slug}/public-salon";
        if (slug === undefined || slug === null)
            throw new globalThis.Error("The parameter 'slug' must be defined.");
        url_ = url_.replace("{slug}", encodeURIComponent("" + slug));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processPublicBookingSalon_Get(_response);
        });
    }

    protected processPublicBookingSalon_Get(response: Response): Promise<PublicBookingSalonInfoDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as PublicBookingSalonInfoDto;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<PublicBookingSalonInfoDto>(null as any);
    }

    publicClientDiagnostics_ReportClientError(request: ClientErrorReportRequest): Promise<void> {
        let url_ = this.baseUrl + "/api/booking-diagnostics/client-error";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(request);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processPublicClientDiagnostics_ReportClientError(_response);
        });
    }

    protected processPublicClientDiagnostics_ReportClientError(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 204) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    publicOtp_RequestOtp(slug: string, id: string, request: RequestOtpRequest): Promise<FileResponse> {
        let url_ = this.baseUrl + "/api/booking/{slug}/public-appointment/{id}/request-otp";
        if (slug === undefined || slug === null)
            throw new globalThis.Error("The parameter 'slug' must be defined.");
        url_ = url_.replace("{slug}", encodeURIComponent("" + slug));
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(request);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/octet-stream"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processPublicOtp_RequestOtp(_response);
        });
    }

    protected processPublicOtp_RequestOtp(response: Response): Promise<FileResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200 || status === 206) {
            const contentDisposition = response.headers ? response.headers.get("content-disposition") : undefined;
            let fileNameMatch = contentDisposition ? /filename\*=(?:(\\?['"])(.*?)\1|(?:[^\s]+'.*?')?([^;\n]*))/g.exec(contentDisposition) : undefined;
            let fileName = fileNameMatch && fileNameMatch.length > 1 ? fileNameMatch[3] || fileNameMatch[2] : undefined;
            if (fileName) {
                fileName = decodeURIComponent(fileName);
            } else {
                fileNameMatch = contentDisposition ? /filename="?([^"]*?)"?(;|$)/g.exec(contentDisposition) : undefined;
                fileName = fileNameMatch && fileNameMatch.length > 1 ? fileNameMatch[1] : undefined;
            }
            return response.blob().then(blob => { return { fileName: fileName, data: blob, status: status, headers: _headers }; });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<FileResponse>(null as any);
    }

    publicOtp_VerifyOtp(slug: string, id: string, request: VerifyOtpRequest): Promise<VerifyOtpResult> {
        let url_ = this.baseUrl + "/api/booking/{slug}/public-appointment/{id}/verify-otp";
        if (slug === undefined || slug === null)
            throw new globalThis.Error("The parameter 'slug' must be defined.");
        url_ = url_.replace("{slug}", encodeURIComponent("" + slug));
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(request);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processPublicOtp_VerifyOtp(_response);
        });
    }

    protected processPublicOtp_VerifyOtp(response: Response): Promise<VerifyOtpResult> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as VerifyOtpResult;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<VerifyOtpResult>(null as any);
    }

    publicOtp_ConfirmWithSession(slug: string, id: string, request: ConfirmWithSessionRequest): Promise<VerifyOtpResult> {
        let url_ = this.baseUrl + "/api/booking/{slug}/public-appointment/{id}/confirm-with-session";
        if (slug === undefined || slug === null)
            throw new globalThis.Error("The parameter 'slug' must be defined.");
        url_ = url_.replace("{slug}", encodeURIComponent("" + slug));
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(request);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processPublicOtp_ConfirmWithSession(_response);
        });
    }

    protected processPublicOtp_ConfirmWithSession(response: Response): Promise<VerifyOtpResult> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as VerifyOtpResult;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<VerifyOtpResult>(null as any);
    }

    publicSelfService_RequestOtp(slug: string, request: SelfServiceContactRequest): Promise<FileResponse> {
        let url_ = this.baseUrl + "/api/booking/{slug}/self-service/request-otp";
        if (slug === undefined || slug === null)
            throw new globalThis.Error("The parameter 'slug' must be defined.");
        url_ = url_.replace("{slug}", encodeURIComponent("" + slug));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(request);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/octet-stream"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processPublicSelfService_RequestOtp(_response);
        });
    }

    protected processPublicSelfService_RequestOtp(response: Response): Promise<FileResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200 || status === 206) {
            const contentDisposition = response.headers ? response.headers.get("content-disposition") : undefined;
            let fileNameMatch = contentDisposition ? /filename\*=(?:(\\?['"])(.*?)\1|(?:[^\s]+'.*?')?([^;\n]*))/g.exec(contentDisposition) : undefined;
            let fileName = fileNameMatch && fileNameMatch.length > 1 ? fileNameMatch[3] || fileNameMatch[2] : undefined;
            if (fileName) {
                fileName = decodeURIComponent(fileName);
            } else {
                fileNameMatch = contentDisposition ? /filename="?([^"]*?)"?(;|$)/g.exec(contentDisposition) : undefined;
                fileName = fileNameMatch && fileNameMatch.length > 1 ? fileNameMatch[1] : undefined;
            }
            return response.blob().then(blob => { return { fileName: fileName, data: blob, status: status, headers: _headers }; });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<FileResponse>(null as any);
    }

    publicSelfService_VerifyOtp(slug: string, request: SelfServiceVerifyRequest): Promise<SelfServiceVerifyResponse> {
        let url_ = this.baseUrl + "/api/booking/{slug}/self-service/verify-otp";
        if (slug === undefined || slug === null)
            throw new globalThis.Error("The parameter 'slug' must be defined.");
        url_ = url_.replace("{slug}", encodeURIComponent("" + slug));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(request);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processPublicSelfService_VerifyOtp(_response);
        });
    }

    protected processPublicSelfService_VerifyOtp(response: Response): Promise<SelfServiceVerifyResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as SelfServiceVerifyResponse;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<SelfServiceVerifyResponse>(null as any);
    }

    publicSelfService_List(slug: string): Promise<SelfServiceAppointmentDto[]> {
        let url_ = this.baseUrl + "/api/booking/{slug}/self-service/appointments";
        if (slug === undefined || slug === null)
            throw new globalThis.Error("The parameter 'slug' must be defined.");
        url_ = url_.replace("{slug}", encodeURIComponent("" + slug));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processPublicSelfService_List(_response);
        });
    }

    protected processPublicSelfService_List(response: Response): Promise<SelfServiceAppointmentDto[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as SelfServiceAppointmentDto[];
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<SelfServiceAppointmentDto[]>(null as any);
    }

    publicSelfService_Cancel(slug: string, id: string): Promise<FileResponse> {
        let url_ = this.baseUrl + "/api/booking/{slug}/self-service/appointments/{id}/cancel";
        if (slug === undefined || slug === null)
            throw new globalThis.Error("The parameter 'slug' must be defined.");
        url_ = url_.replace("{slug}", encodeURIComponent("" + slug));
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "POST",
            headers: {
                "Accept": "application/octet-stream"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processPublicSelfService_Cancel(_response);
        });
    }

    protected processPublicSelfService_Cancel(response: Response): Promise<FileResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200 || status === 206) {
            const contentDisposition = response.headers ? response.headers.get("content-disposition") : undefined;
            let fileNameMatch = contentDisposition ? /filename\*=(?:(\\?['"])(.*?)\1|(?:[^\s]+'.*?')?([^;\n]*))/g.exec(contentDisposition) : undefined;
            let fileName = fileNameMatch && fileNameMatch.length > 1 ? fileNameMatch[3] || fileNameMatch[2] : undefined;
            if (fileName) {
                fileName = decodeURIComponent(fileName);
            } else {
                fileNameMatch = contentDisposition ? /filename="?([^"]*?)"?(;|$)/g.exec(contentDisposition) : undefined;
                fileName = fileNameMatch && fileNameMatch.length > 1 ? fileNameMatch[1] : undefined;
            }
            return response.blob().then(blob => { return { fileName: fileName, data: blob, status: status, headers: _headers }; });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<FileResponse>(null as any);
    }

    publicSelfService_Reschedule(slug: string, id: string, request: SelfServiceRescheduleRequest): Promise<FileResponse> {
        let url_ = this.baseUrl + "/api/booking/{slug}/self-service/appointments/{id}/reschedule";
        if (slug === undefined || slug === null)
            throw new globalThis.Error("The parameter 'slug' must be defined.");
        url_ = url_.replace("{slug}", encodeURIComponent("" + slug));
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(request);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/octet-stream"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processPublicSelfService_Reschedule(_response);
        });
    }

    protected processPublicSelfService_Reschedule(response: Response): Promise<FileResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200 || status === 206) {
            const contentDisposition = response.headers ? response.headers.get("content-disposition") : undefined;
            let fileNameMatch = contentDisposition ? /filename\*=(?:(\\?['"])(.*?)\1|(?:[^\s]+'.*?')?([^;\n]*))/g.exec(contentDisposition) : undefined;
            let fileName = fileNameMatch && fileNameMatch.length > 1 ? fileNameMatch[3] || fileNameMatch[2] : undefined;
            if (fileName) {
                fileName = decodeURIComponent(fileName);
            } else {
                fileNameMatch = contentDisposition ? /filename="?([^"]*?)"?(;|$)/g.exec(contentDisposition) : undefined;
                fileName = fileNameMatch && fileNameMatch.length > 1 ? fileNameMatch[1] : undefined;
            }
            return response.blob().then(blob => { return { fileName: fileName, data: blob, status: status, headers: _headers }; });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<FileResponse>(null as any);
    }
}

export interface AppointmentSlotDto {
    slot?: string;
    isPreferred?: boolean;
}

export interface BookingMonthAvailabilityDto {
    isClosed?: boolean;
    opensOn?: string | undefined;
    days?: MonthDayAvailabilityDto[];
}

export interface MonthDayAvailabilityDto {
    date?: string;
    availableCount?: number;
    isWorkingDay?: boolean;
}

export interface BookingEmployeeDto {
    id?: string;
    firstName?: string;
    lastName?: string;
    hasUpcomingSchedule?: boolean;
}

export interface UploadInspirationResponse {
    url?: string;
    thumbnailUrl?: string;
    key?: string;
}

export interface ServiceCategoryDto {
    id?: string;
    name?: string;
    orderIndex?: number;
}

export interface BookingServiceDto {
    id?: string;
    categoryId?: string | undefined;
    name?: string;
    price?: Money;
    durationInMinutes?: number;
    maxAmount?: number | undefined;
    durationMinMinutes?: number | undefined;
    durationMaxMinutes?: number | undefined;
    comboGroup?: string | undefined;
    hidePrice?: boolean;
    orderIndex?: number;
    isAddon?: boolean;
    addonServiceIds?: string[] | undefined;
    description?: string | undefined;
    images?: BookingServiceImageDto[] | undefined;
}

export interface Money {
    amount?: number;
    currency?: string;
}

export interface BookingServiceImageDto {
    url?: string;
    thumbnailUrl?: string;
    orderIndex?: number;
}

export interface PublicBookingHoldDto {
    appointmentId?: string;
    lease?: HoldLease;
}

export interface HoldLease {
    reservationToken?: string;
    expiryTimeUtc?: string;
}

export interface CreateAppointmentDto {
    serviceIds?: string[];
    employeeId?: string;
    date?: string;
    startTime?: string;
    turnstileToken?: string | undefined;
}

export interface UpdateAppointmentDto {
    token?: string;
    serviceIds?: string[];
    employeeId?: string;
    date?: string;
    startTime?: string;
    turnstileToken?: string | undefined;
}

export interface PublicBookingSalonInfoDto {
    name?: string;
    slug?: string;
    customerVerificationChannel?: number;
    bookingAccessPolicy?: number;
    isBookingAvailable?: boolean;
    requireCustomerName?: boolean;
    collectInstagramHandle?: boolean;
    collectInspirationImages?: boolean;
    isBookingPaused?: boolean;
    bookingPauseMessage?: string | undefined;
    bookingCalendarColorHex?: string | undefined;
    bookingCalendarBackgroundHex?: string | undefined;
    bookingCalendarSurfaceHex?: string | undefined;
    bookingCalendarPriceHex?: string | undefined;
    termsOfService?: string | undefined;
    isPlatformMaintenance?: boolean;
    platformMaintenanceMessage?: string | undefined;
    bookingHorizonDays?: number;
}

export interface ClientErrorReportRequest {
    correlationId?: string | undefined;
    operation?: string | undefined;
    kind?: string | undefined;
    message?: string | undefined;
    status?: number | undefined;
    salonSlug?: string | undefined;
    pageUrl?: string | undefined;
    context?: string | undefined;
}

export interface RequestOtpRequest {
    token?: string;
    phoneNumber?: string | undefined;
    email?: string | undefined;
    turnstileToken?: string | undefined;
    firstName?: string | undefined;
    lastName?: string | undefined;
    isReturningCustomer?: boolean;
}

export interface VerifyOtpResult {
    requiresManualConfirmation?: boolean;
    sessionToken?: string | undefined;
    sessionExpiresAtUtc?: string | undefined;
    inspirationUploadToken?: string | undefined;
}

export interface VerifyOtpRequest {
    token?: string;
    otp?: string;
    firstName?: string | undefined;
    lastName?: string | undefined;
    instagramNick?: string | undefined;
}

export interface ConfirmWithSessionRequest {
    token?: string;
    sessionToken?: string;
    turnstileToken?: string | undefined;
    firstName?: string | undefined;
    lastName?: string | undefined;
    instagramNick?: string | undefined;
}

export interface SelfServiceContactRequest {
    email?: string | undefined;
    phoneNumber?: string | undefined;
    turnstileToken?: string | undefined;
}

export interface SelfServiceVerifyResponse {
    sessionToken?: string;
    expiresAtUtc?: string;
}

export interface SelfServiceVerifyRequest {
    email?: string | undefined;
    phoneNumber?: string | undefined;
    otp?: string;
}

export interface SelfServiceAppointmentDto {
    id?: string;
    employeeId?: string;
    serviceId?: string;
    serviceIds?: string[];
    serviceName?: string;
    employeeFirstName?: string;
    employeeLastName?: string;
    date?: string;
    startTime?: string;
    endTime?: string;
    status?: string;
    canCancel?: boolean;
    canReschedule?: boolean;
}

export interface SelfServiceRescheduleRequest {
    employeeId?: string;
    serviceId?: string;
    date?: string;
    startTime?: string;
}

export interface FileParameter {
    data: any;
    fileName: string;
}

export interface FileResponse {
    data: Blob;
    status: number;
    fileName?: string;
    headers?: { [name: string]: any };
}

export class BookingApiException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isBookingApiException = true;

    static isBookingApiException(obj: any): obj is BookingApiException {
        return obj.isBookingApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    if (result !== null && result !== undefined)
        throw result;
    else
        throw new BookingApiException(message, status, response, headers, null);
}