// <auto-generated />
using System;
using App.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace App.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260603074435_ShiftTemplateFixedStartTimes")]
    partial class ShiftTemplateFixedStartTimes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("App.Domain.Aggregates.AppointmentAggregate.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AnonSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("anon_session_id");

                    b.Property<string>("AppointmentNotes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<DateTime?>("LinkExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("link_expires_at_utc");

                    b.Property<DateTime?>("PaidAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at_utc");

                    b.Property<string>("PaymentLinkUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("payment_link_url");

                    b.Property<string>("PaymentSessionId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("payment_session_id");

                    b.Property<int>("PaymentStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("payment_status");

                    b.Property<DateTime?>("Reminder24hSentAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reminder_24h_sent_at_utc");

                    b.Property<DateTime?>("Reminder2hSentAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reminder_2h_sent_at_utc");

                    b.Property<int?>("SelfServiceChangeKind")
                        .HasColumnType("integer")
                        .HasColumnName("self_service_change_kind");

                    b.Property<DateTimeOffset?>("SelfServiceChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("self_service_changed_at");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid");

                    b.Property<int>("Source")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("source");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("AnonSessionId")
                        .HasFilter("anon_session_id IS NOT NULL");

                    b.HasIndex("CustomerId");

                    b.HasIndex("SelfServiceChangedAt")
                        .HasFilter("self_service_changed_at IS NOT NULL");

                    b.HasIndex("ServiceId");

                    b.HasIndex("PaymentStatus", "LinkExpiresAtUtc")
                        .HasFilter("payment_status = 1");

                    b.HasIndex("Status", "Date");

                    b.HasIndex("EmployeeId", "Date", "StartTime")
                        .IsUnique()
                        .HasFilter("\"Status\" <> 'Canceled'");

                    b.HasIndex("TenantId", "Date", "EmployeeId");

                    b.ToTable("Appointments", (string)null);
                });

            modelBuilder.Entity("App.Domain.Aggregates.CustomerAggregate.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("GeneralNotes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("InstagramNick")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("instagram_nick");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsWhitelisted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_whitelisted");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PhoneNumberSearch")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Source")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("source");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Email");

                    b.HasIndex("TenantId", "PhoneNumber");

                    b.HasIndex("TenantId", "PhoneNumberSearch");

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("App.Domain.Aggregates.EmployeeAggregate.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<int>("SlotGenerationMode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("slot_generation_mode");

                    b.Property<string>("Specialization")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("specialization");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("user_id IS NOT NULL");

                    b.ToTable("Employees", (string)null);
                });

            modelBuilder.Entity("App.Domain.Aggregates.EmployeeAggregate.ShiftTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("SlotGenerationMode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("slot_generation_mode");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.ToTable("ShiftTemplates", (string)null);
                });

            modelBuilder.Entity("App.Domain.Aggregates.ImpersonationAggregate.ImpersonationSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AdminUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("admin_user_id");

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at_utc");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip_address");

                    b.Property<bool>("IsReadOnly")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_read_only");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<Guid>("TargetTenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("AdminUserId");

                    b.HasIndex("TargetTenantId");

                    b.HasIndex("EndedAtUtc", "ExpiresAtUtc");

                    b.ToTable("impersonation_sessions", (string)null);
                });

            modelBuilder.Entity("App.Domain.Aggregates.NotificationAggregate.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ReadAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RecipientUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ShortText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CreatedAtUtc");

                    b.HasIndex("TenantId", "ReadAtUtc");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("App.Domain.Aggregates.NotificationAggregate.NotificationUsageRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Channel")
                        .HasColumnType("integer");

                    b.Property<decimal>("Points")
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime>("SentAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "SentAtUtc");

                    b.HasIndex("TenantId", "Channel", "SentAtUtc");

                    b.ToTable("NotificationUsage", (string)null);
                });

            modelBuilder.Entity("App.Domain.Aggregates.PromoCodeAggregate.PromoCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AppliesTo")
                        .HasColumnType("integer")
                        .HasColumnName("applies_to");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentUses")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("current_uses");

                    b.Property<int>("DiscountType")
                        .HasColumnType("integer")
                        .HasColumnName("discount_type");

                    b.Property<decimal>("DiscountValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("discount_value");

                    b.Property<int?>("DurationMonths")
                        .HasColumnType("integer")
                        .HasColumnName("duration_months");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<int?>("MaxTotalUses")
                        .HasColumnType("integer")
                        .HasColumnName("max_total_uses");

                    b.Property<int>("MaxUsesPerTenant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("max_uses_per_tenant");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTime?>("ValidUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_until");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.ToTable("promo_codes", (string)null);
                });

            modelBuilder.Entity("App.Domain.Aggregates.SelfServiceAggregate.SelfServiceOtp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("Consumed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FailedAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("PhoneE164")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("SessionExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SessionToken")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc");

                    b.HasIndex("SessionToken");

                    b.HasIndex("TenantId", "Email");

                    b.HasIndex("TenantId", "PhoneE164");

                    b.ToTable("SelfServiceOtps", (string)null);
                });

            modelBuilder.Entity("App.Domain.Aggregates.ServiceAggregate.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<decimal?>("DepositOverrideValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("deposit_override_value");

                    b.Property<int>("DurationInMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_in_minutes");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("VatRateId")
                        .HasColumnType("uuid")
                        .HasColumnName("vat_rate_id");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("VatRateId");

                    b.ToTable("Services", (string)null);
                });

            modelBuilder.Entity("App.Domain.Aggregates.ServiceAggregate.ServiceCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer")
                        .HasColumnName("order_index");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.ToTable("ServiceCategories", (string)null);
                });

            modelBuilder.Entity("App.Domain.Aggregates.ShortLinkAggregate.ShortLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AppointmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("appointment_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("purpose");

                    b.Property<string>("TargetUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("target_url");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ShortLinks", (string)null);
                });

            modelBuilder.Entity("App.Domain.Aggregates.TenantAggregate.PromoCodeRedemption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DiscountSnapshot")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("discount_snapshot");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<Guid>("PromoCodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("promo_code_id");

                    b.Property<DateTime>("RedeemedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("redeemed_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("PromoCodeId");

                    b.HasIndex("TenantId", "IsActive");

                    b.ToTable("promo_code_redemptions", (string)null);
                });

            modelBuilder.Entity("App.Domain.Aggregates.TenantAggregate.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AppointmentConfirmationMode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("appointment_confirmation_mode");

                    b.Property<int>("AppointmentSlotStepMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(15)
                        .HasColumnName("appointment_slot_step_minutes");

                    b.Property<int>("BookingAccessPolicy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("booking_access_policy");

                    b.Property<bool>("CollectInstagramHandle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("collect_instagram_handle");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("PLN")
                        .HasColumnName("currency");

                    b.Property<int>("CustomerVerificationChannel")
                        .HasColumnType("integer")
                        .HasColumnName("customer_verification_channel");

                    b.Property<DateTime?>("DemoCreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("demo_created_at_utc");

                    b.Property<bool>("IsDemo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_demo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<bool>("RequireCustomerName")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("require_customer_name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<int>("StaffCalendarVisibilityPolicy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("staff_calendar_visibility_policy");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("Europe/Warsaw")
                        .HasColumnName("time_zone_id");

                    b.HasKey("Id");

                    b.HasIndex("IsDemo", "DemoCreatedAtUtc")
                        .HasDatabaseName("ix_tenants_is_demo_demo_created_at_utc");

                    b.ToTable("Tenants", (string)null);
                });

            modelBuilder.Entity("App.Domain.Aggregates.UserAggregate.PhoneConfirmationOtp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptsCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_phone_confirmation_otps_active_per_user")
                        .HasFilter("\"ConsumedAt\" IS NULL");

                    b.ToTable("PhoneConfirmationOtps", (string)null);
                });

            modelBuilder.Entity("App.Domain.Aggregates.UserAggregate.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("EmailConfirmed", "CreatedAt")
                        .HasDatabaseName("IX_Users_EmailConfirmed_CreatedAt");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("VatRate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Value")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique();

                    b.ToTable("VatRates", (string)null);
                });

            modelBuilder.Entity("App.Domain.Aggregates.AppointmentAggregate.Appointment", b =>
                {
                    b.HasOne("App.Domain.Aggregates.CustomerAggregate.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("App.Domain.Aggregates.EmployeeAggregate.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("App.Domain.Aggregates.ServiceAggregate.Service", null)
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("App.Domain.Aggregates.TenantAggregate.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Money", "DepositAmount", b1 =>
                        {
                            b1.Property<Guid>("AppointmentId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("deposit_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("deposit_currency");

                            b1.HasKey("AppointmentId");

                            b1.ToTable("Appointments");

                            b1.WithOwner()
                                .HasForeignKey("AppointmentId");
                        });

                    b.OwnsOne("Money", "TotalPrice", b1 =>
                        {
                            b1.Property<Guid>("AppointmentId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("total_price_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("total_price_currency");

                            b1.HasKey("AppointmentId");

                            b1.ToTable("Appointments");

                            b1.WithOwner()
                                .HasForeignKey("AppointmentId");
                        });

                    b.OwnsOne("App.Domain.Aggregates.AppointmentAggregate.OtpVerification", "OtpVerification", b1 =>
                        {
                            b1.Property<Guid>("AppointmentId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Channel")
                                .HasColumnType("integer")
                                .HasColumnName("otp_channel");

                            b1.Property<string>("Email")
                                .HasMaxLength(254)
                                .HasColumnType("character varying(254)")
                                .HasColumnName("otp_email");

                            b1.Property<DateTime>("ExpiryTimeUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("otp_expiry_utc");

                            b1.Property<string>("OtpHash")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("otp_hash");

                            b1.Property<string>("PhoneE164")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("otp_phone_e164");

                            b1.HasKey("AppointmentId");

                            b1.ToTable("Appointments");

                            b1.WithOwner()
                                .HasForeignKey("AppointmentId");
                        });

                    b.OwnsOne("HoldLease", "Lease", b1 =>
                        {
                            b1.Property<Guid>("AppointmentId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("ExpiryTimeUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("lease_expiry_utc");

                            b1.Property<Guid>("ReservationToken")
                                .HasColumnType("uuid")
                                .HasColumnName("lease_reservation_token");

                            b1.HasKey("AppointmentId");

                            b1.ToTable("Appointments");

                            b1.WithOwner()
                                .HasForeignKey("AppointmentId");
                        });

                    b.Navigation("DepositAmount");

                    b.Navigation("Lease");

                    b.Navigation("OtpVerification");

                    b.Navigation("TotalPrice")
                        .IsRequired();
                });

            modelBuilder.Entity("App.Domain.Aggregates.CustomerAggregate.Customer", b =>
                {
                    b.HasOne("App.Domain.Aggregates.TenantAggregate.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("App.Domain.Aggregates.EmployeeAggregate.Employee", b =>
                {
                    b.HasOne("App.Domain.Aggregates.TenantAggregate.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("App.Domain.Aggregates.UserAggregate.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsMany("App.Domain.Aggregates.EmployeeAggregate.EmployeeLeave", "Leaves", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("Id");

                            b1.Property<int>("AbsenceStatus")
                                .HasColumnType("integer")
                                .HasColumnName("AbsenceStatus");

                            b1.Property<int>("AbsenceType")
                                .HasColumnType("integer")
                                .HasColumnName("AbsenceType");

                            b1.Property<Guid>("EmployeeId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("EmployeeId");

                            b1.ToTable("EmployeeLeaves", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("EmployeeId");

                            b1.OwnsOne("DateRange", "DateRange", b2 =>
                                {
                                    b2.Property<Guid>("EmployeeLeaveId")
                                        .HasColumnType("uuid");

                                    b2.Property<DateOnly>("EndDate")
                                        .HasColumnType("date")
                                        .HasColumnName("EndDate");

                                    b2.Property<DateOnly>("StartDate")
                                        .HasColumnType("date")
                                        .HasColumnName("StartDate");

                                    b2.HasKey("EmployeeLeaveId");

                                    b2.ToTable("EmployeeLeaves");

                                    b2.WithOwner()
                                        .HasForeignKey("EmployeeLeaveId");
                                });

                            b1.Navigation("DateRange")
                                .IsRequired();
                        });

                    b.OwnsMany("App.Domain.Aggregates.EmployeeAggregate.EmployeeService", "Services", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<int>("CustomDuration")
                                .HasColumnType("integer")
                                .HasColumnName("custom_duration");

                            b1.Property<Guid>("EmployeeId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("ServiceId")
                                .HasColumnType("uuid")
                                .HasColumnName("service_id");

                            b1.Property<Guid>("TenantId")
                                .HasColumnType("uuid")
                                .HasColumnName("tenant_id");

                            b1.HasKey("Id");

                            b1.HasIndex("EmployeeId");

                            b1.HasIndex("ServiceId");

                            b1.HasIndex("TenantId", "EmployeeId", "ServiceId")
                                .IsUnique();

                            b1.ToTable("EmployeeServices", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("EmployeeId");

                            b1.HasOne("App.Domain.Aggregates.ServiceAggregate.Service", null)
                                .WithMany()
                                .HasForeignKey("ServiceId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.HasOne("App.Domain.Aggregates.TenantAggregate.Tenant", null)
                                .WithMany()
                                .HasForeignKey("TenantId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.OwnsOne("Money", "CustomPrice", b2 =>
                                {
                                    b2.Property<Guid>("EmployeeServiceId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 2)
                                        .HasColumnType("numeric(18,2)")
                                        .HasColumnName("price_amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("price_currency");

                                    b2.HasKey("EmployeeServiceId");

                                    b2.ToTable("EmployeeServices");

                                    b2.WithOwner()
                                        .HasForeignKey("EmployeeServiceId");
                                });

                            b1.Navigation("CustomPrice");
                        });

                    b.OwnsMany("App.Domain.Aggregates.EmployeeAggregate.EmployeeSchedule", "Schedules", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int>("NumberOfCycles")
                                .HasColumnType("integer")
                                .HasColumnName("number_of_cycles");

                            b1.Property<Guid>("employee_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("employee_id");

                            b1.ToTable("EmployeeSchedules", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("employee_id");

                            b1.OwnsOne("DateRange", "ActiveRange", b2 =>
                                {
                                    b2.Property<Guid>("EmployeeScheduleId")
                                        .HasColumnType("uuid");

                                    b2.Property<DateOnly>("EndDate")
                                        .HasColumnType("date")
                                        .HasColumnName("active_to");

                                    b2.Property<DateOnly>("StartDate")
                                        .HasColumnType("date")
                                        .HasColumnName("active_from");

                                    b2.HasKey("EmployeeScheduleId");

                                    b2.ToTable("EmployeeSchedules");

                                    b2.WithOwner()
                                        .HasForeignKey("EmployeeScheduleId");
                                });

                            b1.OwnsMany("App.Domain.Aggregates.EmployeeAggregate.ScheduleDay", "ScheduleDays", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<int>("CycleIndex")
                                        .HasColumnType("integer")
                                        .HasColumnName("cycle_index");

                                    b2.PrimitiveCollection<TimeOnly[]>("FixedStartTimes")
                                        .IsRequired()
                                        .HasColumnType("time without time zone[]")
                                        .HasColumnName("fixed_start_times");

                                    b2.Property<Guid>("employee_schedule_id")
                                        .HasColumnType("uuid");

                                    b2.HasKey("Id");

                                    b2.HasIndex("employee_schedule_id");

                                    b2.ToTable("ScheduleDays", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("employee_schedule_id");

                                    b2.OwnsMany("App.Domain.Common.TimeRange", "Breaks", b3 =>
                                        {
                                            b3.Property<Guid>("Id")
                                                .ValueGeneratedOnAdd()
                                                .HasColumnType("uuid")
                                                .HasColumnName("id");

                                            b3.Property<TimeOnly>("EndTime")
                                                .HasColumnType("time without time zone")
                                                .HasColumnName("end_time");

                                            b3.Property<TimeOnly>("StartTime")
                                                .HasColumnType("time without time zone")
                                                .HasColumnName("start_time");

                                            b3.Property<Guid>("schedule_day_id")
                                                .HasColumnType("uuid");

                                            b3.HasKey("Id");

                                            b3.HasIndex("schedule_day_id");

                                            b3.ToTable("ScheduleDayBreaks", (string)null);

                                            b3.WithOwner()
                                                .HasForeignKey("schedule_day_id");
                                        });

                                    b2.OwnsMany("App.Domain.Common.TimeRange", "WorkRanges", b3 =>
                                        {
                                            b3.Property<Guid>("Id")
                                                .ValueGeneratedOnAdd()
                                                .HasColumnType("uuid")
                                                .HasColumnName("id");

                                            b3.Property<TimeOnly>("EndTime")
                                                .HasColumnType("time without time zone")
                                                .HasColumnName("end_time");

                                            b3.Property<TimeOnly>("StartTime")
                                                .HasColumnType("time without time zone")
                                                .HasColumnName("start_time");

                                            b3.Property<Guid>("schedule_day_id")
                                                .HasColumnType("uuid");

                                            b3.HasKey("Id");

                                            b3.HasIndex("schedule_day_id");

                                            b3.ToTable("ScheduleDayWorkRanges", (string)null);

                                            b3.WithOwner()
                                                .HasForeignKey("schedule_day_id");
                                        });

                                    b2.Navigation("Breaks");

                                    b2.Navigation("WorkRanges");
                                });

                            b1.Navigation("ActiveRange")
                                .IsRequired();

                            b1.Navigation("ScheduleDays");
                        });

                    b.OwnsMany("App.Domain.Aggregates.EmployeeAggregate.ScheduleOverride", "Overrides", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateOnly>("Date")
                                .HasColumnType("date")
                                .HasColumnName("date");

                            b1.Property<Guid>("employee_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("employee_id");

                            b1.ToTable("ScheduleOverrides", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("employee_id");

                            b1.OwnsOne("App.Domain.Aggregates.EmployeeAggregate.ScheduleDay", "ScheduleDay", b2 =>
                                {
                                    b2.Property<Guid>("ScheduleOverrideId")
                                        .HasColumnType("uuid");

                                    b2.Property<int?>("CycleIndex")
                                        .HasColumnType("integer")
                                        .HasColumnName("cycle_index");

                                    b2.PrimitiveCollection<TimeOnly[]>("FixedStartTimes")
                                        .IsRequired()
                                        .HasColumnType("time without time zone[]")
                                        .HasColumnName("fixed_start_times");

                                    b2.Property<Guid>("Id")
                                        .HasColumnType("uuid");

                                    b2.HasKey("ScheduleOverrideId");

                                    b2.ToTable("ScheduleOverrides");

                                    b2.WithOwner()
                                        .HasForeignKey("ScheduleOverrideId");

                                    b2.OwnsMany("App.Domain.Common.TimeRange", "Breaks", b3 =>
                                        {
                                            b3.Property<Guid>("Id")
                                                .ValueGeneratedOnAdd()
                                                .HasColumnType("uuid")
                                                .HasColumnName("id");

                                            b3.Property<TimeOnly>("EndTime")
                                                .HasColumnType("time without time zone")
                                                .HasColumnName("end_time");

                                            b3.Property<TimeOnly>("StartTime")
                                                .HasColumnType("time without time zone")
                                                .HasColumnName("start_time");

                                            b3.Property<Guid>("schedule_override_id")
                                                .HasColumnType("uuid");

                                            b3.HasKey("Id");

                                            b3.HasIndex("schedule_override_id");

                                            b3.ToTable("ScheduleOverrideBreaks", (string)null);

                                            b3.WithOwner()
                                                .HasForeignKey("schedule_override_id");
                                        });

                                    b2.OwnsMany("App.Domain.Common.TimeRange", "WorkRanges", b3 =>
                                        {
                                            b3.Property<Guid>("Id")
                                                .ValueGeneratedOnAdd()
                                                .HasColumnType("uuid")
                                                .HasColumnName("id");

                                            b3.Property<TimeOnly>("EndTime")
                                                .HasColumnType("time without time zone")
                                                .HasColumnName("end_time");

                                            b3.Property<TimeOnly>("StartTime")
                                                .HasColumnType("time without time zone")
                                                .HasColumnName("start_time");

                                            b3.Property<Guid>("schedule_override_id")
                                                .HasColumnType("uuid");

                                            b3.HasKey("Id");

                                            b3.HasIndex("schedule_override_id");

                                            b3.ToTable("ScheduleOverrideWorkRanges", (string)null);

                                            b3.WithOwner()
                                                .HasForeignKey("schedule_override_id");
                                        });

                                    b2.Navigation("Breaks");

                                    b2.Navigation("WorkRanges");
                                });

                            b1.Navigation("ScheduleDay")
                                .IsRequired();
                        });

                    b.Navigation("Leaves");

                    b.Navigation("Overrides");

                    b.Navigation("Schedules");

                    b.Navigation("Services");
                });

            modelBuilder.Entity("App.Domain.Aggregates.EmployeeAggregate.ShiftTemplate", b =>
                {
                    b.OwnsOne("App.Domain.Aggregates.EmployeeAggregate.ScheduleDay", "ScheduleDay", b1 =>
                        {
                            b1.Property<Guid>("ShiftTemplateId")
                                .HasColumnType("uuid");

                            b1.Property<int?>("CycleIndex")
                                .HasColumnType("integer")
                                .HasColumnName("cycle_index");

                            b1.PrimitiveCollection<TimeOnly[]>("FixedStartTimes")
                                .IsRequired()
                                .HasColumnType("time without time zone[]")
                                .HasColumnName("fixed_start_times");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.HasKey("ShiftTemplateId");

                            b1.ToTable("ShiftTemplates");

                            b1.WithOwner()
                                .HasForeignKey("ShiftTemplateId");

                            b1.OwnsMany("App.Domain.Common.TimeRange", "Breaks", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<TimeOnly>("EndTime")
                                        .HasColumnType("time without time zone")
                                        .HasColumnName("end_time");

                                    b2.Property<TimeOnly>("StartTime")
                                        .HasColumnType("time without time zone")
                                        .HasColumnName("start_time");

                                    b2.Property<Guid>("shift_template_id")
                                        .HasColumnType("uuid");

                                    b2.HasKey("Id");

                                    b2.HasIndex("shift_template_id");

                                    b2.ToTable("ShiftTemplateBreaks", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("shift_template_id");
                                });

                            b1.OwnsMany("App.Domain.Common.TimeRange", "WorkRanges", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<TimeOnly>("EndTime")
                                        .HasColumnType("time without time zone")
                                        .HasColumnName("end_time");

                                    b2.Property<TimeOnly>("StartTime")
                                        .HasColumnType("time without time zone")
                                        .HasColumnName("start_time");

                                    b2.Property<Guid>("shift_template_id")
                                        .HasColumnType("uuid");

                                    b2.HasKey("Id");

                                    b2.HasIndex("shift_template_id");

                                    b2.ToTable("ShiftTemplateWorkRanges", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("shift_template_id");
                                });

                            b1.Navigation("Breaks");

                            b1.Navigation("WorkRanges");
                        });

                    b.Navigation("ScheduleDay")
                        .IsRequired();
                });

            modelBuilder.Entity("App.Domain.Aggregates.NotificationAggregate.Notification", b =>
                {
                    b.HasOne("App.Domain.Aggregates.TenantAggregate.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("App.Domain.Aggregates.NotificationAggregate.NotificationUsageRecord", b =>
                {
                    b.HasOne("App.Domain.Aggregates.TenantAggregate.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("App.Domain.Aggregates.SelfServiceAggregate.SelfServiceOtp", b =>
                {
                    b.HasOne("App.Domain.Aggregates.TenantAggregate.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("App.Domain.Aggregates.ServiceAggregate.Service", b =>
                {
                    b.HasOne("App.Domain.Aggregates.ServiceAggregate.ServiceCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VatRate", null)
                        .WithMany()
                        .HasForeignKey("VatRateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Money", "Price", b1 =>
                        {
                            b1.Property<Guid>("ServiceId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("price_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("price_currency");

                            b1.HasKey("ServiceId");

                            b1.ToTable("Services");

                            b1.WithOwner()
                                .HasForeignKey("ServiceId");
                        });

                    b.Navigation("Price")
                        .IsRequired();
                });

            modelBuilder.Entity("App.Domain.Aggregates.TenantAggregate.PromoCodeRedemption", b =>
                {
                    b.HasOne("App.Domain.Aggregates.PromoCodeAggregate.PromoCode", null)
                        .WithMany()
                        .HasForeignKey("PromoCodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("App.Domain.Aggregates.TenantAggregate.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("App.Domain.Aggregates.TenantAggregate.Tenant", b =>
                {
                    b.OwnsOne("App.Domain.Aggregates.TenantAggregate.DepositSettings", "DepositSettings", b1 =>
                        {
                            b1.Property<Guid>("TenantId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("Enabled")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("deposit_enabled");

                            b1.Property<int>("Instrument")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasDefaultValue(0)
                                .HasColumnName("deposit_instrument");

                            b1.Property<int>("Mode")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasDefaultValue(0)
                                .HasColumnName("deposit_mode");

                            b1.Property<decimal>("Value")
                                .ValueGeneratedOnAdd()
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasDefaultValue(0m)
                                .HasColumnName("deposit_value");

                            b1.HasKey("TenantId");

                            b1.ToTable("Tenants");

                            b1.WithOwner()
                                .HasForeignKey("TenantId");
                        });

                    b.OwnsOne("App.Domain.Aggregates.TenantAggregate.GapFillingSettings", "GapFillingSettings", b1 =>
                        {
                            b1.Property<Guid>("TenantId")
                                .HasColumnType("uuid");

                            b1.Property<int>("BufferMinutes")
                                .HasColumnType("integer")
                                .HasColumnName("gap_filling_buffer_minutes");

                            b1.Property<int>("LookaheadSlots")
                                .HasColumnType("integer")
                                .HasColumnName("gap_filling_lookahead_slots");

                            b1.Property<int>("Mode")
                                .HasColumnType("integer")
                                .HasColumnName("gap_filling_mode");

                            b1.HasKey("TenantId");

                            b1.ToTable("Tenants");

                            b1.WithOwner()
                                .HasForeignKey("TenantId");
                        });

                    b.OwnsOne("App.Domain.Aggregates.TenantAggregate.MerchantAccount", "MerchantAccount", b1 =>
                        {
                            b1.Property<Guid>("TenantId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AccountId")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("merchant_account_id");

                            b1.Property<bool>("ChargesEnabled")
                                .HasColumnType("boolean")
                                .HasColumnName("merchant_charges_enabled");

                            b1.Property<int>("OnboardingStatus")
                                .HasColumnType("integer")
                                .HasColumnName("merchant_onboarding_status");

                            b1.Property<string>("Provider")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("merchant_provider");

                            b1.HasKey("TenantId");

                            b1.ToTable("Tenants");

                            b1.WithOwner()
                                .HasForeignKey("TenantId");
                        });

                    b.OwnsOne("App.Domain.Aggregates.TenantAggregate.NotificationSettings", "NotificationSettings", b1 =>
                        {
                            b1.Property<Guid>("TenantId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("AppointmentReminder2hToCustomer")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("notify_appointment_reminder_2h_to_customer");

                            b1.Property<bool>("AppointmentReminderToCustomer")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(true)
                                .HasColumnName("notify_appointment_reminder_to_customer");

                            b1.Property<bool>("AwaitingConfirmationToSalon")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(true)
                                .HasColumnName("notify_awaiting_confirmation_to_salon");

                            b1.Property<bool>("BookingConfirmationToCustomer")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("notify_booking_confirmation_to_customer");

                            b1.Property<bool>("CancellationToCustomer")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(true)
                                .HasColumnName("notify_cancellation_to_customer");

                            b1.Property<bool>("CancellationToSalon")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(true)
                                .HasColumnName("notify_cancellation_to_salon");

                            b1.Property<bool>("CancelledBySalonToCustomer")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(true)
                                .HasColumnName("notify_cancelled_by_salon_to_customer");

                            b1.Property<bool>("NewBookingToSalon")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(true)
                                .HasColumnName("notify_new_booking_to_salon");

                            b1.Property<bool>("RescheduleToCustomer")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(true)
                                .HasColumnName("notify_reschedule_to_customer");

                            b1.Property<bool>("RescheduleToSalon")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(true)
                                .HasColumnName("notify_reschedule_to_salon");

                            b1.Property<bool>("RescheduledBySalonToCustomer")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(true)
                                .HasColumnName("notify_rescheduled_by_salon_to_customer");

                            b1.Property<bool>("StaffBookedAppointmentToCustomer")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(true)
                                .HasColumnName("notify_staff_booked_appointment_to_customer");

                            b1.HasKey("TenantId");

                            b1.ToTable("Tenants");

                            b1.WithOwner()
                                .HasForeignKey("TenantId");
                        });

                    b.OwnsOne("App.Domain.Aggregates.TenantAggregate.Subscription", "Subscription", b1 =>
                        {
                            b1.Property<Guid>("TenantId")
                                .HasColumnType("uuid");

                            b1.Property<Guid?>("ActivePromoCodeRedemptionId")
                                .HasColumnType("uuid")
                                .HasColumnName("subscription_active_promo_code_redemption_id");

                            b1.Property<DateTimeOffset?>("CurrentPeriodEndsAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("subscription_current_period_ends_at");

                            b1.Property<bool>("IsFoundingMember")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("subscription_is_founding_member");

                            b1.Property<int?>("MonthlySmsHardCap")
                                .HasColumnType("integer")
                                .HasColumnName("subscription_monthly_sms_hard_cap");

                            b1.Property<int>("Seats")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasDefaultValue(1)
                                .HasColumnName("subscription_seats");

                            b1.Property<int>("Status")
                                .HasColumnType("integer")
                                .HasColumnName("subscription_status");

                            b1.Property<DateTimeOffset?>("TrialEndsAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("subscription_trial_ends_at");

                            b1.HasKey("TenantId");

                            b1.ToTable("Tenants");

                            b1.WithOwner()
                                .HasForeignKey("TenantId");
                        });

                    b.Navigation("DepositSettings")
                        .IsRequired();

                    b.Navigation("GapFillingSettings");

                    b.Navigation("MerchantAccount");

                    b.Navigation("NotificationSettings")
                        .IsRequired();

                    b.Navigation("Subscription")
                        .IsRequired();
                });

            modelBuilder.Entity("App.Domain.Aggregates.UserAggregate.PhoneConfirmationOtp", b =>
                {
                    b.HasOne("App.Domain.Aggregates.UserAggregate.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("App.Domain.Aggregates.UserAggregate.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("App.Domain.Aggregates.UserAggregate.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Domain.Aggregates.UserAggregate.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("App.Domain.Aggregates.UserAggregate.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VatRate", b =>
                {
                    b.HasOne("App.Domain.Aggregates.TenantAggregate.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
