// <auto-generated />
using System;
using App.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace App.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260509094126_MultiWorkRanges")]
    partial class MultiWorkRanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("App.Domain.Aggregates.AppointmentAggregate.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AppointmentNotes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("EmployeeId", "Date", "StartTime")
                        .IsUnique()
                        .HasFilter("\"Status\" <> 'Canceled'");

                    b.HasIndex("TenantId", "Date", "EmployeeId");

                    b.ToTable("Appointments", (string)null);
                });

            modelBuilder.Entity("App.Domain.Aggregates.CustomerAggregate.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("GeneralNotes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "PhoneNumber");

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("App.Domain.Aggregates.EmployeeAggregate.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("user_id IS NOT NULL");

                    b.ToTable("Employees", (string)null);
                });

            modelBuilder.Entity("App.Domain.Aggregates.EmployeeAggregate.ShiftTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.ToTable("ShiftTemplates", (string)null);
                });

            modelBuilder.Entity("App.Domain.Aggregates.ServiceAggregate.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<int>("DurationInMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_in_minutes");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("VatRateId")
                        .HasColumnType("uuid")
                        .HasColumnName("vat_rate_id");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("VatRateId");

                    b.ToTable("Services", (string)null);
                });

            modelBuilder.Entity("App.Domain.Aggregates.ServiceAggregate.ServiceCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer")
                        .HasColumnName("order_index");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.ToTable("ServiceCategories", (string)null);
                });

            modelBuilder.Entity("App.Domain.Aggregates.TenantAggregate.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AppointmentSlotStepMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(15)
                        .HasColumnName("appointment_slot_step_minutes");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("PLN")
                        .HasColumnName("currency");

                    b.Property<int>("CustomerVerificationChannel")
                        .HasColumnType("integer")
                        .HasColumnName("customer_verification_channel");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("Europe/Warsaw")
                        .HasColumnName("time_zone_id");

                    b.HasKey("Id");

                    b.ToTable("Tenants", (string)null);
                });

            modelBuilder.Entity("App.Domain.Aggregates.UserAggregate.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("VatRate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Value")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique();

                    b.ToTable("VatRates", (string)null);
                });

            modelBuilder.Entity("App.Domain.Aggregates.AppointmentAggregate.Appointment", b =>
                {
                    b.HasOne("App.Domain.Aggregates.CustomerAggregate.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("App.Domain.Aggregates.EmployeeAggregate.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("App.Domain.Aggregates.ServiceAggregate.Service", null)
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("App.Domain.Aggregates.TenantAggregate.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Money", "TotalPrice", b1 =>
                        {
                            b1.Property<Guid>("AppointmentId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("total_price_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("total_price_currency");

                            b1.HasKey("AppointmentId");

                            b1.ToTable("Appointments");

                            b1.WithOwner()
                                .HasForeignKey("AppointmentId");
                        });

                    b.OwnsOne("App.Domain.Aggregates.AppointmentAggregate.OtpVerification", "OtpVerification", b1 =>
                        {
                            b1.Property<Guid>("AppointmentId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Channel")
                                .HasColumnType("integer")
                                .HasColumnName("otp_channel");

                            b1.Property<string>("Email")
                                .HasMaxLength(254)
                                .HasColumnType("character varying(254)")
                                .HasColumnName("otp_email");

                            b1.Property<DateTime>("ExpiryTimeUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("otp_expiry_utc");

                            b1.Property<string>("OtpHash")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("otp_hash");

                            b1.Property<string>("PhoneE164")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("otp_phone_e164");

                            b1.HasKey("AppointmentId");

                            b1.ToTable("Appointments");

                            b1.WithOwner()
                                .HasForeignKey("AppointmentId");
                        });

                    b.OwnsOne("HoldLease", "Lease", b1 =>
                        {
                            b1.Property<Guid>("AppointmentId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("ExpiryTimeUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("lease_expiry_utc");

                            b1.Property<Guid>("ReservationToken")
                                .HasColumnType("uuid")
                                .HasColumnName("lease_reservation_token");

                            b1.HasKey("AppointmentId");

                            b1.ToTable("Appointments");

                            b1.WithOwner()
                                .HasForeignKey("AppointmentId");
                        });

                    b.Navigation("Lease");

                    b.Navigation("OtpVerification");

                    b.Navigation("TotalPrice")
                        .IsRequired();
                });

            modelBuilder.Entity("App.Domain.Aggregates.CustomerAggregate.Customer", b =>
                {
                    b.HasOne("App.Domain.Aggregates.TenantAggregate.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("App.Domain.Aggregates.EmployeeAggregate.Employee", b =>
                {
                    b.HasOne("App.Domain.Aggregates.TenantAggregate.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("App.Domain.Aggregates.UserAggregate.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsMany("App.Domain.Aggregates.EmployeeAggregate.EmployeeLeave", "Leaves", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("Id");

                            b1.Property<Guid>("EmployeeId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("EmployeeId");

                            b1.ToTable("EmployeeLeaves", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("EmployeeId");

                            b1.OwnsOne("DateRange", "DateRange", b2 =>
                                {
                                    b2.Property<Guid>("EmployeeLeaveId")
                                        .HasColumnType("uuid");

                                    b2.Property<DateOnly>("EndDate")
                                        .HasColumnType("date")
                                        .HasColumnName("EndDate");

                                    b2.Property<DateOnly>("StartDate")
                                        .HasColumnType("date")
                                        .HasColumnName("StartDate");

                                    b2.HasKey("EmployeeLeaveId");

                                    b2.ToTable("EmployeeLeaves");

                                    b2.WithOwner()
                                        .HasForeignKey("EmployeeLeaveId");
                                });

                            b1.Navigation("DateRange")
                                .IsRequired();
                        });

                    b.OwnsMany("App.Domain.Aggregates.EmployeeAggregate.EmployeeService", "Services", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<int>("CustomDuration")
                                .HasColumnType("integer")
                                .HasColumnName("custom_duration");

                            b1.Property<Guid>("EmployeeId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("ServiceId")
                                .HasColumnType("uuid")
                                .HasColumnName("service_id");

                            b1.Property<Guid>("TenantId")
                                .HasColumnType("uuid")
                                .HasColumnName("tenant_id");

                            b1.HasKey("Id");

                            b1.HasIndex("EmployeeId");

                            b1.HasIndex("ServiceId");

                            b1.HasIndex("TenantId", "EmployeeId", "ServiceId")
                                .IsUnique();

                            b1.ToTable("EmployeeServices", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("EmployeeId");

                            b1.HasOne("App.Domain.Aggregates.ServiceAggregate.Service", null)
                                .WithMany()
                                .HasForeignKey("ServiceId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.HasOne("App.Domain.Aggregates.TenantAggregate.Tenant", null)
                                .WithMany()
                                .HasForeignKey("TenantId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.OwnsOne("Money", "CustomPrice", b2 =>
                                {
                                    b2.Property<Guid>("EmployeeServiceId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 2)
                                        .HasColumnType("numeric(18,2)")
                                        .HasColumnName("price_amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("price_currency");

                                    b2.HasKey("EmployeeServiceId");

                                    b2.ToTable("EmployeeServices");

                                    b2.WithOwner()
                                        .HasForeignKey("EmployeeServiceId");
                                });

                            b1.Navigation("CustomPrice");
                        });

                    b.OwnsMany("App.Domain.Aggregates.EmployeeAggregate.EmployeeSchedule", "Schedules", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int>("NumberOfCycles")
                                .HasColumnType("integer")
                                .HasColumnName("number_of_cycles");

                            b1.Property<Guid>("employee_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("employee_id");

                            b1.ToTable("EmployeeSchedules", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("employee_id");

                            b1.OwnsOne("DateRange", "ActiveRange", b2 =>
                                {
                                    b2.Property<Guid>("EmployeeScheduleId")
                                        .HasColumnType("uuid");

                                    b2.Property<DateOnly>("EndDate")
                                        .HasColumnType("date")
                                        .HasColumnName("active_to");

                                    b2.Property<DateOnly>("StartDate")
                                        .HasColumnType("date")
                                        .HasColumnName("active_from");

                                    b2.HasKey("EmployeeScheduleId");

                                    b2.ToTable("EmployeeSchedules");

                                    b2.WithOwner()
                                        .HasForeignKey("EmployeeScheduleId");
                                });

                            b1.OwnsMany("App.Domain.Aggregates.EmployeeAggregate.ScheduleDay", "ScheduleDays", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<int>("CycleIndex")
                                        .HasColumnType("integer")
                                        .HasColumnName("cycle_index");

                                    b2.Property<Guid>("employee_schedule_id")
                                        .HasColumnType("uuid");

                                    b2.HasKey("Id");

                                    b2.HasIndex("employee_schedule_id");

                                    b2.ToTable("ScheduleDays", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("employee_schedule_id");

                                    b2.OwnsMany("App.Domain.Common.TimeRange", "Breaks", b3 =>
                                        {
                                            b3.Property<Guid>("Id")
                                                .ValueGeneratedOnAdd()
                                                .HasColumnType("uuid")
                                                .HasColumnName("id");

                                            b3.Property<TimeOnly>("EndTime")
                                                .HasColumnType("time without time zone")
                                                .HasColumnName("end_time");

                                            b3.Property<TimeOnly>("StartTime")
                                                .HasColumnType("time without time zone")
                                                .HasColumnName("start_time");

                                            b3.Property<Guid>("schedule_day_id")
                                                .HasColumnType("uuid");

                                            b3.HasKey("Id");

                                            b3.HasIndex("schedule_day_id");

                                            b3.ToTable("ScheduleDayBreaks", (string)null);

                                            b3.WithOwner()
                                                .HasForeignKey("schedule_day_id");
                                        });

                                    b2.OwnsMany("App.Domain.Common.TimeRange", "WorkRanges", b3 =>
                                        {
                                            b3.Property<Guid>("Id")
                                                .ValueGeneratedOnAdd()
                                                .HasColumnType("uuid")
                                                .HasColumnName("id");

                                            b3.Property<TimeOnly>("EndTime")
                                                .HasColumnType("time without time zone")
                                                .HasColumnName("end_time");

                                            b3.Property<TimeOnly>("StartTime")
                                                .HasColumnType("time without time zone")
                                                .HasColumnName("start_time");

                                            b3.Property<Guid>("schedule_day_id")
                                                .HasColumnType("uuid");

                                            b3.HasKey("Id");

                                            b3.HasIndex("schedule_day_id");

                                            b3.ToTable("ScheduleDayWorkRanges", (string)null);

                                            b3.WithOwner()
                                                .HasForeignKey("schedule_day_id");
                                        });

                                    b2.Navigation("Breaks");

                                    b2.Navigation("WorkRanges");
                                });

                            b1.Navigation("ActiveRange")
                                .IsRequired();

                            b1.Navigation("ScheduleDays");
                        });

                    b.OwnsMany("App.Domain.Aggregates.EmployeeAggregate.ScheduleOverride", "Overrides", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateOnly>("Date")
                                .HasColumnType("date")
                                .HasColumnName("date");

                            b1.Property<Guid>("employee_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("employee_id");

                            b1.ToTable("ScheduleOverrides", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("employee_id");

                            b1.OwnsOne("App.Domain.Aggregates.EmployeeAggregate.ScheduleDay", "ScheduleDay", b2 =>
                                {
                                    b2.Property<Guid>("ScheduleOverrideId")
                                        .HasColumnType("uuid");

                                    b2.Property<int?>("CycleIndex")
                                        .HasColumnType("integer")
                                        .HasColumnName("cycle_index");

                                    b2.Property<Guid>("Id")
                                        .HasColumnType("uuid");

                                    b2.HasKey("ScheduleOverrideId");

                                    b2.ToTable("ScheduleOverrides");

                                    b2.WithOwner()
                                        .HasForeignKey("ScheduleOverrideId");

                                    b2.OwnsMany("App.Domain.Common.TimeRange", "Breaks", b3 =>
                                        {
                                            b3.Property<Guid>("Id")
                                                .ValueGeneratedOnAdd()
                                                .HasColumnType("uuid")
                                                .HasColumnName("id");

                                            b3.Property<TimeOnly>("EndTime")
                                                .HasColumnType("time without time zone")
                                                .HasColumnName("end_time");

                                            b3.Property<TimeOnly>("StartTime")
                                                .HasColumnType("time without time zone")
                                                .HasColumnName("start_time");

                                            b3.Property<Guid>("schedule_override_id")
                                                .HasColumnType("uuid");

                                            b3.HasKey("Id");

                                            b3.HasIndex("schedule_override_id");

                                            b3.ToTable("ScheduleOverrideBreaks", (string)null);

                                            b3.WithOwner()
                                                .HasForeignKey("schedule_override_id");
                                        });

                                    b2.OwnsMany("App.Domain.Common.TimeRange", "WorkRanges", b3 =>
                                        {
                                            b3.Property<Guid>("Id")
                                                .ValueGeneratedOnAdd()
                                                .HasColumnType("uuid")
                                                .HasColumnName("id");

                                            b3.Property<TimeOnly>("EndTime")
                                                .HasColumnType("time without time zone")
                                                .HasColumnName("end_time");

                                            b3.Property<TimeOnly>("StartTime")
                                                .HasColumnType("time without time zone")
                                                .HasColumnName("start_time");

                                            b3.Property<Guid>("schedule_override_id")
                                                .HasColumnType("uuid");

                                            b3.HasKey("Id");

                                            b3.HasIndex("schedule_override_id");

                                            b3.ToTable("ScheduleOverrideWorkRanges", (string)null);

                                            b3.WithOwner()
                                                .HasForeignKey("schedule_override_id");
                                        });

                                    b2.Navigation("Breaks");

                                    b2.Navigation("WorkRanges");
                                });

                            b1.Navigation("ScheduleDay")
                                .IsRequired();
                        });

                    b.Navigation("Leaves");

                    b.Navigation("Overrides");

                    b.Navigation("Schedules");

                    b.Navigation("Services");
                });

            modelBuilder.Entity("App.Domain.Aggregates.EmployeeAggregate.ShiftTemplate", b =>
                {
                    b.OwnsOne("App.Domain.Aggregates.EmployeeAggregate.ScheduleDay", "ScheduleDay", b1 =>
                        {
                            b1.Property<Guid>("ShiftTemplateId")
                                .HasColumnType("uuid");

                            b1.Property<int?>("CycleIndex")
                                .HasColumnType("integer")
                                .HasColumnName("cycle_index");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.HasKey("ShiftTemplateId");

                            b1.ToTable("ShiftTemplates");

                            b1.WithOwner()
                                .HasForeignKey("ShiftTemplateId");

                            b1.OwnsMany("App.Domain.Common.TimeRange", "Breaks", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<TimeOnly>("EndTime")
                                        .HasColumnType("time without time zone")
                                        .HasColumnName("end_time");

                                    b2.Property<TimeOnly>("StartTime")
                                        .HasColumnType("time without time zone")
                                        .HasColumnName("start_time");

                                    b2.Property<Guid>("shift_template_id")
                                        .HasColumnType("uuid");

                                    b2.HasKey("Id");

                                    b2.HasIndex("shift_template_id");

                                    b2.ToTable("ShiftTemplateBreaks", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("shift_template_id");
                                });

                            b1.OwnsMany("App.Domain.Common.TimeRange", "WorkRanges", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<TimeOnly>("EndTime")
                                        .HasColumnType("time without time zone")
                                        .HasColumnName("end_time");

                                    b2.Property<TimeOnly>("StartTime")
                                        .HasColumnType("time without time zone")
                                        .HasColumnName("start_time");

                                    b2.Property<Guid>("shift_template_id")
                                        .HasColumnType("uuid");

                                    b2.HasKey("Id");

                                    b2.HasIndex("shift_template_id");

                                    b2.ToTable("ShiftTemplateWorkRanges", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("shift_template_id");
                                });

                            b1.Navigation("Breaks");

                            b1.Navigation("WorkRanges");
                        });

                    b.Navigation("ScheduleDay")
                        .IsRequired();
                });

            modelBuilder.Entity("App.Domain.Aggregates.ServiceAggregate.Service", b =>
                {
                    b.HasOne("App.Domain.Aggregates.ServiceAggregate.ServiceCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VatRate", null)
                        .WithMany()
                        .HasForeignKey("VatRateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Money", "Price", b1 =>
                        {
                            b1.Property<Guid>("ServiceId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("price_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("price_currency");

                            b1.HasKey("ServiceId");

                            b1.ToTable("Services");

                            b1.WithOwner()
                                .HasForeignKey("ServiceId");
                        });

                    b.Navigation("Price")
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("App.Domain.Aggregates.UserAggregate.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("App.Domain.Aggregates.UserAggregate.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Domain.Aggregates.UserAggregate.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("App.Domain.Aggregates.UserAggregate.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VatRate", b =>
                {
                    b.HasOne("App.Domain.Aggregates.TenantAggregate.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
